import type { ParsedInstagramPost, ParsedTweet } from "./types";
import { timestampParser } from "./utils";

const FIELD_LABELS: Record<string, string> = {
  archived_urlkey: "Archived URL Key",
  archived_timestamp: "Archived Timestamp",
  parsed_archived_timestamp: "Archived Timestamp (parsed)",
  archived_tweet_url: "Archived Tweet URL",
  parsed_archived_tweet_url: "Parsed Archived Tweet URL",
  original_tweet_url: "Original Tweet URL",
  parsed_tweet_url: "Parsed Tweet URL",
  available_tweet_text: "Available Tweet Text",
  available_tweet_is_RT: "Available Tweet Is Retweet",
  available_tweet_info: "Available Tweet Info",
  archived_post_url: "Archived Post URL",
  parsed_archived_post_url: "Parsed Archived Post URL",
  original_post_url: "Original Post URL",
  parsed_post_url: "Parsed Post URL",
  archived_mimetype: "Archived MIME Type",
  archived_statuscode: "Archived Status Code",
  archived_digest: "Archived Digest",
  archived_length: "Archived Length",
  resumption_key: "Resumption Key",
};

const FIELD_ORDER = [
  "parsed_archived_timestamp",
  "archived_timestamp",
  "archived_tweet_url",
  "parsed_archived_tweet_url",
  "original_tweet_url",
  "parsed_tweet_url",
  "available_tweet_text",
  "available_tweet_is_RT",
  "available_tweet_info",
  "archived_mimetype",
  "archived_statuscode",
  "archived_digest",
  "archived_length",
  "archived_urlkey",
  "resumption_key",
] as const;

export function buildTweetsHtml(username: string, tweets: (ParsedTweet | ParsedInstagramPost)[]): string {
  const summary = `Total captures: ${tweets.length}`;

  const cards = tweets
    .map((tweet, index) => renderTweetCard(tweet, index))
    .join("\n");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Archived tweets of @${escapeHtml(username)}</title>
  <style>
    :root {
      color-scheme: light dark;
      font-family: system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
      background-color: #f7f7f8;
      color: #111827;
    }
    body {
      margin: 0;
      padding: 24px;
      background: #f7f7f8;
      color: #111827;
    }
    header {
      max-width: 960px;
      margin: 0 auto 32px;
    }
    h1 {
      font-size: 1.8rem;
      margin-bottom: 0.5rem;
    }
    p.meta {
      color: #4b5563;
      margin: 0;
    }
    main {
      display: grid;
      gap: 16px;
      max-width: 960px;
      margin: 0 auto;
    }
    article {
      border: 1px solid #e5e7eb;
      border-radius: 16px;
      background: #ffffff;
      padding: 20px;
      box-shadow: 0 10px 30px rgba(15, 23, 42, 0.06);
    }
    article header {
      margin: 0 0 12px;
    }
    h2 {
      font-size: 1.125rem;
      margin: 0;
    }
    dl {
      display: grid;
      grid-template-columns: minmax(160px, 220px) 1fr;
      gap: 8px 16px;
      margin: 0;
      font-size: 0.95rem;
    }
    dt {
      font-weight: 600;
      color: #374151;
    }
    dd {
      margin: 0;
      color: #1f2937;
      word-break: break-word;
      white-space: pre-wrap;
    }
    a {
      color: #2563eb;
      text-decoration: none;
    }
    a:hover, a:focus {
      text-decoration: underline;
    }
    footer {
      margin-top: 48px;
      text-align: center;
      color: #6b7280;
      font-size: 0.875rem;
    }
    @media (prefers-color-scheme: dark) {
      :root, body {
        background: #0f172a;
        color: #e2e8f0;
      }
      article {
        background: #111827;
        border-color: #1f2937;
      }
      dt {
        color: #cbd5f5;
      }
      dd {
        color: #e2e8f0;
      }
      a {
        color: #60a5fa;
      }
      p.meta {
        color: #94a3b8;
      }
      footer {
        color: #94a3b8;
      }
    }
  </style>
</head>
<body>
  <header>
    <h1>Archived tweets of @${escapeHtml(username)}</h1>
    <p class="meta">${escapeHtml(summary)}</p>
  </header>
  <main>
    ${cards}
  </main>
  <footer>
    Data sourced via the Internet Archive CDX API. Generated by Snapshot Explorer.
  </footer>
</body>
</html>`;
}

function renderTweetCard(tweet: ParsedTweet | ParsedInstagramPost, index: number): string {
  const tweetRecord = tweet as Record<string, string | boolean | null>;
  const rows = FIELD_ORDER.filter((field) => tweetRecord[field] !== undefined).map((field) => {
    let value = tweetRecord[field];
    if (field === "parsed_archived_timestamp" && !value && tweetRecord.archived_timestamp) {
      value = timestampParser(String(tweetRecord.archived_timestamp));
    }

    const label = FIELD_LABELS[field] ?? field;
    const formatted = formatValue(field, value);
    return `<dt>${escapeHtml(label)}</dt><dd>${formatted}</dd>`;
  });

  return `
    <article>
      <header>
        <h2>Capture #${index + 1}</h2>
      </header>
      <dl>
        ${rows.join("\n")}
      </dl>
    </article>
  `;
}

function formatValue(field: string, value: unknown): string {
  if (value === null || value === undefined || value === "") {
    return `<span aria-hidden="true">-</span>`;
  }

  if (typeof value === "boolean") {
    return value ? "Yes" : "No";
  }

  const text = String(value);
  if (/^https?:\/\//i.test(text)) {
    const label = field.includes("archived") ? "Open archived" : "Open link";
    return `<a href="${escapeHtml(text)}" target="_blank" rel="noopener noreferrer">${escapeHtml(label)}</a>`;
  }

  return escapeHtml(text);
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}
